version: 2.1

orbs:
  pfe: pantheon-systems/front-end@0.4.0
  queue: eddiewebb/queue@1.5.0

workflows:
  build-preview-test-deploy:
    jobs:
      - pfe/gatsby-build-and-deploy:
          use-yarn: false
          deployment-path: docs
          # https://circleci.com/docs/2.0/configuration-reference/#docker-executor
          # https://github.com/pantheon-systems/frontend-orbs#parameters
          resource-class: large
          incremental-build: true
          gcp-bucket: "static.pantheonfrontend.website"
          gatsby-cache-version: "v1.8.23"
          pre-steps:
            - checkout
            - run:
                name: Import Functions and Variables
                command: .circleci/scripts/set-env.sh && source $BASH_ENV
            - run:
                name: Install PHP
                command: sudo apt-get update && sudo apt-get install -y php-cli php-xml
            - run:
                name: Install Terminus
                command: |
                  php .circleci/scripts/terminus-installer.php
            - run:
                name: Import Tokens
                command: gatsby-tokens
            - run:
                name: Import External Data
                command: .circleci/scripts/import-external-data.sh
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - ./
                  - ./public
      - test-links:
          requires:
            - pfe/gatsby-build-and-deploy
      - deploy:
          requires:
            - test-links
          filters:
            branches:
              only: main

jobs:
  test-links:
    docker:
      - image: cimg/php:8.1.7-browsers
        environment:
          BUILD_PATH: /home/circleci/project
    working_directory: ~/project
    steps:
      - pfe/set-terminus-env
      - checkout
      - run:
          name: Import Functions and Variables
          command: .circleci/scripts/set-env.sh && source $BASH_ENV
      - run:
          name: Install Broken Link Checker
          command: sudo npm install --location=global broken-link-checker
      - run:
          name: Check for merge conflicts
          command: .circleci/scripts/merge_conflicts.sh
      - run:
          name: Test links
          command: .circleci/tests/link-checker.sh
            "https://${TERMINUS_ENV}--${TERMINUS_SITE}.my.pantheonfrontend.website/docs"
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

  deploy:
    docker:
      - image: cimg/php:8.1.7-node
        environment:
          BUILD_PATH: /home/circleci/project
    working_directory: ~/project
    steps:
      - queue/until_front_of_line:
          time: '15'
      - run: echo "Waiting for other deployments to main to complete"
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Import Functions and Variables
          command: .circleci/scripts/set-env.sh && source $BASH_ENV
      - run:
          name: Install rsync
          command: sudo apt-get update && sudo apt-get install -y rsync
      - run:
          name: Install Terminus
          command: php .circleci/scripts/terminus-installer.php
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              .circleci/scripts/deploy-live.sh
            fi
          no_output_timeout: 15m
      - store_artifacts:
          path: deployment-log.txt
          destination: deployment-log.txt
